### ISSUE TITLE
Proposed SDL example changes

### ISSUE THREAD

**Issue by DevJac** [haskell-game/sdl2#116]
`SDL.hs` has the following example:
```
{-# LANGUAGE OverloadedStrings #-}
module Main where

import SDL
import Linear (V4(..))
import Control.Monad (unless)

main :: IO ()
main = do
  initialize [InitEverything]
  window <- createWindow "My SDL Application" defaultWindow
  renderer <- createRenderer window (-1) defaultRenderer
  appLoop renderer

appLoop :: Renderer -> IO ()
appLoop renderer = do
  events <- pollEvents
  let eventIsQPress event =
        case eventPayload event of
          KeyboardEvent keyboardEvent ->
            keyboardEventKeyMotion keyboardEvent == Pressed &&
            keysymKeycode (keyboardEventKeysym keyboardEvent) == KeycodeQ
          _ -> False
      qPressed = not (null (filter eventIsQPress events))
  rendererDrawColor renderer $= V4 0 0 255 255
  clear renderer
  present renderer
  unless qPressed (appLoop renderer)
```

I propose making 2 changes:

1. Change `initialize [InitEverything]` to `initializeAll`.

2. Change `qPressed = not (null (filter eventIsQPress events))` to `qPressed = any eventIsQPress events`.

The reason for the first change is that `InitEverything` is deprecated, and the reason for the second is that hlint complains about the "null . filter" portion, and because I consider it simpler and more readable to use `any`.

If anyone is in favor of these change, I am willing to make the PR myself if needed.

**Comment by tejon** [comment]
I'm not a primary maintainer, but absolutely in favor of updating examples. All of the `lazyfoo`/`twinklebear` stuff got only minimal make-it-build updates for the 2.0 API changes, and for that matter they're not highly idiomatic in the first place (especially `lazybear`, IIRC) since they're based directly on C++ originals.

Actually, I've been thinking for some time now that we might be better off just keeping the spirit of each lesson but rewriting the code from scratch using smaller functions -- most of which would, once written, stay identical in later lessons (this being a lesson in and of itself). And a `main` which contains only initialization, not the example logic. Etc... just demonstrate better Haskell (and general FP) practices in general.

**Comment by DevJac** [comment]
Since at least one other person thinks this is a good idea, I created PRs #117 and #118. I have not done anything with the larger tutorials, I do not have the expertise for that right now, but I will be using those tutorial and may propose further changes.

**Comment by ocharles** [comment]
I don't object to changes to the examples that increase readability.

**Comment by tejon** [comment]
These PRs are merged.
