### ISSUE TITLE
Getting Started link in README is broken

### ISSUE THREAD

**Issue by WildYorkies** [haskell-game/sdl2#186]
https://hackage.haskell.org/package/sdl2/docs/SDL.html

This is taking me to a wrong location.
![image](https://user-images.githubusercontent.com/1299322/43051076-57758ebe-8dc8-11e8-8be3-e4f22960ce96.png)

And then clicking on the other link that it shows doesn't work either.

**Comment by tejon** [comment]
Hackage has been notoriously bad about building documentation for a while now. Stackage has it: https://www.stackage.org/lts-12.2/package/sdl2-2.4.1.0

I'm not sure switching to Stackage as the primary docs link is a good idea, though, because there will be cases where a newer version is available on Hackage.

**Comment by ocharles** [comment]
Thanks, I forgot to upload documentation when I cut the last release. Should all be sorted now.
