### ISSUE TITLE
Improve documentation on how to install sdl2 under Windows

### ISSUE THREAD

**Issue by ocharles** [haskell-game/sdl2#83]
[This Reddit post](https://www.reddit.com/r/haskellgamedev/comments/3kvm7z/building_and_installing_sdl2_200_sdl2image/) contains a description of how to get `sdl2` installed under Windows. I don't know if this is the expected process, but if it is, we should add it to the `README`, and maybe the `description` field in the Cabal file (so it is very prominent on http://hackage.haskell.org/package/sdl2).

**Comment by tejon** [comment]
There are "better" ways to do some of that but they're much harder to explain, and anyone who already has the relevant knowledge should be able to figure them out from those instructions anyway.

There *was* a significantly easier process involving MSYS2, but since my Windows 10 upgrade that seems to be broken (the bindings still build, but dependent programs can't find a needed library because for some reason they're looking for a `.a` instead of a `.dll`) so at present this is probably the best works-for-everyone solution.

**Comment by tejon** [comment]
This is in pretty good shape now. Closing, re-open if anyone's still having real difficulty.
