### ISSUE TITLE
`surfaceColorKey` shouldn't use `Word32` as a colour format

### ISSUE THREAD

**Issue by sindriava** [haskell-game/sdl2#84]
At the moment, `surfaceColorKey` has the signature of `surfaceColorKey :: Surface -> StateVar (Maybe Word32)`. This is probably because it should use a colour key in the pixel format of the surface, and the function that does that returns a `Word32`.

Possible fixes are:
 - Make `surfaceColorKey` use `V4 Word8` and retrieve the pixel format under the hood, since the surface is being passed as a parameter anyways
 - Mandate the usage of the surface's pixel colour format by using an opaque data type
 - Mention this in the docs for `surfaceColorKey`

**Comment by ocharles** [comment]
I don't think we can use a vector as the return type, because you don't necessarily get a colour value back from `mapRGB`. If you have an 8-bit surface with a palette, you instead get an index into a palette, not the colour of that element of the palette.

Just mentioning it in the docs isn't great, which means I'm more in favour of option two.

Anyone else got any thoughts? If we do go with a (semi-)opaque data type (I would still expose the constructor), what should we call it? `SurfaceColour`?

**Comment by ocharles** [comment]
Actually, this doesn't mention the 4th alternative: call `MapRGB` on whatever the user passes in.

I think *this* is what I'd prefer, even if it does have performance implications (but who calls `surfaceColorKey` in a tight inner loop anyway...?)

**Comment by ocharles** [comment]
The `maprgb` branch contains my proposed fix as option 4.

**Comment by tejon** [comment]
> it does have performance implications (but who calls surfaceColorKey in a tight inner loop anyway...? I'm sure I'll regret saying that)

It does sound like the kind of thing that might somehow happen at a prototyping stage and then get forgotten about because the output looks fine, so a documentation note on *this* could be helpful.

**Comment by ocharles** [comment]
The problem is, I'm just not sure what the documentation would add. It would read as "by the way, this is artificially slower than the SDL equivalent and there's.... nothing you can do about it".

**Comment by tejon** [comment]
Stronger guarantees in exchange for not being able to treat the texture itself as a temp variable (which you shouldn't be doing anyway) seems like a perfectly good rationale to me! I can't dismiss the potential wailing of the pre-optimizers, but I like to think people are using a Haskell binding because they want Haskell features. :)

**Comment by sindriava** [comment]
I agree with tejon on this. The whole point of the new API is to make it more idiomatic. If someone wants to do tight optimisation, they could always rewrite the critical part using `SDL.raw`, right? It seems to me that this removal of a friction point and a source of potential bugs is more in line with the safety Haskell provides, than the speed.

It would certainly be nice to include a documentation note that this also calls `mapRGB`, just so it's known and potentially visible to people looking for ways to optimise.

**Comment by ocharles** [comment]
I'm a little confused, but are we all in agreement of the proposed branch I have? Diff is at https://github.com/haskell-game/sdl2/commit/2110266b4cad1280e52261391a2999dd01e8204c. There is some documentation there, but it doesn't spell out that it literally calls `SDL_MapRGBA`.

**Comment by tejon** [comment]
I'm definitely in favor of that proposal. Documentation discussion is (relatively) bikeshedding, we can resolve that later. Maybe get @polarina to weigh in just in case?

**Comment by polarina** [comment]
I'd generally always go with simplicity and ease-of-use until someone can provide definitive benchmarks/profiles that any performance overhead induced is proving to be a problem.

**Comment by ocharles** [comment]
Ok, this has had a week, let's go ahead with my proposal.

**Comment by sindriava** [comment]
Agreed. I'd go with ease of use, for the hardcore optimisers there's always `SDL.Raw`.
